Check SqlState instead of error message
JasperFx/weasel pull request #161
Opened 2024-12-26 20:37 UTC by e-tobi

The PostgreSQL error messages are translated, so trying to match them against an english text might not work on different locales.

Please note, that here a 3 more places where the message text is evaluated, two of them only catching an Exception from reader.CloseAsync(). These lines of code are not not covered by any unit test and I couldn't figure out a sane way to trigger an exception there, so I left them untouched.

2024-12-27 04:51 UTC, mysticmind requested changes
Just to be safe, I would suggest to change this to `e.Message.Contains("does not exist") || e.SqlState == "3F000"`?

2024-12-27 15:27 UTC, e-tobi commented
There are A LOT of messages in PostgreSQL containing "does not exist":

https://github.com/postgres/postgres/blob/master/src/backend/po/de.po

I don't know which ones would make it to an exception, but my guess is "does not exist" is too unspecific.
Best solution would probably be to not rely on an exception at all and explicitly check for the schema existence.

2024-12-31 18:00 UTC, mysticmind commented
@e-tobi I saw the changes what you have done to use `PostgresErrorCodes`, have kick started the CI runs.

2024-12-31 18:02 UTC, mysticmind approved these changes

2025-01-14 17:19 UTC, merged